DATA:
  TRAIN_IMAGE_DIR: '/home/hasnain/Datasets/DIV2k/train'
  VAL_IMAGE_DIR: '/home/hasnain/Datasets/DIV2k/val'
  HIGH_RES_IMAGE_SIZE: 256
  NUM_WORKERS: 4
MODEL:
  BLOCK: 'inverted_residual'
  FEATURE_EXTRACTOR: 'vgg'
  GENERATOR:
    FEATURES: 16
    NUM_BLOCKS: 12
    EXPANSION_FACTOR: 3
    LEARNING_RATE: 0.0002
    WEIGHT_DECAY: 0.002
    ADVERSARIAL_WEIGHT: 0.01
    CONTENT_WEIGHT: 1
    PRETRAIN_EPOCHS: 5
  DISCRIMINATOR:
    FEATURES: 32
    NUM_BLOCKS: 6
    LEARNING_RATE: 0.0003
    WEIGHT_DECAY: 0.001
TRAINING:
  PATIENCE: 100
  BATCH_SIZE: 32
  EPOCHS: 100000
  PRECISION: 32
  ACCELERATOR: 'ddp'
  GPUS: 2
