DATA:
  IMAGE_DIR: '/home/hasnain/Datasets/SeattleSportsScience/images'
  HIGH_RES_IMAGE_SIZE: 256
  NUM_WORKERS: 4
MODEL:
  GENERATOR:
    FEATURES: 32
    NUM_BLOCKS: 6
    EXPANSION_FACTOR: 3
    LEARNING_RATE: 0.0001
    WEIGHT_DECAY: 0.002
    ADVERSARIAL_WEIGHT: 0.001
    CONTENT_WEIGHT: 1
    MSE_WEIGHT: 1
  DISCRIMINATOR:
    FEATURES: 32
    NUM_BLOCKS: 6
    LEARNING_RATE: 0.0001
    WEIGHT_DECAY: 0.002
TRAINING:
  BATCH_SIZE: 32
  EPOCHS: 100
  HALF_PRECISION: false
  GPUS: 1
